spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/manamanam
    username: postgres
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_schema: thymeleaf_sec_test 
    hibernate:
      ddl-auto: create